additional_feature_files: None
allow_subsequent_nan_losses: 10
batch_size: 256
cache_validation_data: true
checkpoint_path: None
clip_gradient_norm: 1
clip_target_to_zero:
- qobs_mm_per_hour
data_dir: data/datadir/CAMELS_US
dataset: hourly_camels_us
device: cuda:0
dynamic_inputs:
- convective_fraction
- longwave_radiation
- potential_energy
- potential_evaporation
- pressure
- shortwave_radiation
- specific_humidity
- temperature
- total_precipitation
- wind_u
- wind_v
embedding_hiddens:
- 30
- 20
- 64
epochs: 60
experiment_name: mtslstm_a_seed444
forcings: nldas_hourly
head: regression
hidden_size: 20
initial_forget_bias: 3
learning_rate:
  0: 0.01
  20: 0.005
  40: 0.001
log_interval: 5
log_n_figures: 0
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
- Alpha-NSE
- Beta-NSE
model: mtslstm
num_workers: 3
number_of_basins: 1
optimizer: Adam
output_activation: linear
output_dropout: 0.4
shared_mtslstm: false
predict_last_n:
  1D: 1
  12H: 2
regularization:
- tie_frequencies
run_dir: runs
save_train_data: false
save_validation_results: false
save_weights_every: 1
seed: 444
seq_length:
  1D: 365
  12H: 360
static_inputs: []
target_variable:
- qobs_mm_per_hour
test_basin_file: 01022500.txt
test_end_date: 30/09/2018
test_start_date: 01/10/2008
train_basin_file: 01022500.txt
train_data_file: None
train_end_date: 30/09/2003
train_start_date: 01/10/1990
transfer_mtslstm_states:
  h: linear
  c: linear
use_frequencies:
- 1D
- 12H
validate_every: 3
validate_n_random_basins: 516
validation_basin_file: 01022500.txt
validation_end_date: 30/09/2008
validation_start_date: 01/10/2003
zero_center_target: true
