additional_feature_files: None
allow_low_frequency_inputs: true
allow_subsequent_nan_losses: 10
batch_size: 256
cache_validation_data: true
camels_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
checkpoint_path: None
clip_gradient_norm: 1
clip_targets_to_zero:
- qobs_mm_per_hour
data_dir: data/datadir/CAMELS_US
dataset: hourly_camels_us
device: cuda:0
dynamic_inputs:
  1H:
  - convective_fraction_nldas_hourly
  - longwave_radiation_nldas_hourly
  - potential_energy_nldas_hourly
  - potential_evaporation_nldas_hourly
  - pressure_nldas_hourly
  - shortwave_radiation_nldas_hourly
  - specific_humidity_nldas_hourly
  - temperature_nldas_hourly
  - total_precipitation_nldas_hourly
  - wind_u_nldas_hourly
  - wind_v_nldas_hourly
  - prcp(mm/day)_daymet
  - srad(W/m2)_daymet
  - tmax(C)_daymet
  - tmin(C)_daymet
  - vp(Pa)_daymet
  - prcp(mm/day)_maurer_extended
  - srad(W/m2)_maurer_extended
  - tmax(C)_maurer_extended
  - tmin(C)_maurer_extended
  - vp(Pa)_maurer_extended
  1D:
  - prcp(mm/day)_daymet
  - srad(W/m2)_daymet
  - tmax(C)_daymet
  - tmin(C)_daymet
  - vp(Pa)_daymet
  - prcp(mm/day)_maurer_extended
  - srad(W/m2)_maurer_extended
  - tmax(C)_maurer_extended
  - tmin(C)_maurer_extended
  - vp(Pa)_maurer_extended
embedding_hiddens:
- 30
- 20
- 64
epochs: 30
experiment_name: mtslstm_multiforcing_dailyhourly_seed666
forcings:
- nldas_hourly
- daymet
- maurer_extended
head: regression
hidden_size:
  1D: 64
  1H: 64
initial_forget_bias: 3
learning_rate:
  0: 0.0005
  10: 0.0001
  25: 5e-05
log_interval: 5
log_n_figures: 0
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
- Alpha-NSE
- Beta-NSE
model: mtslstm
num_workers: 5
number_of_basins: 516
optimizer: Adam
output_activation: linear
output_dropout: 0.4
shared_mtslstm: false
predict_last_n:
  1D: 1
  1H: 24
regularization:
- tie_frequencies
run_dir: runs
save_train_data: false
save_validation_results: false
save_weights_every: 1
seed: 666
seq_length:
  1D: 365
  1H: 336
static_inputs: []
target_variables:
- qobs_mm_per_hour
test_basin_file: data/516_basins.txt
test_end_date: 30/09/2008
test_start_date: 01/10/2003
train_basin_file: data/516_basins.txt
train_data_file: None
train_end_date: 30/09/2003
train_start_date: 01/10/1990
transfer_mtslstm_states:
  h: linear
  c: linear
use_frequencies:
- 1D
- 1H
validate_every: 5
validate_n_random_basins: 516
validation_basin_file: data/516_basins.txt
validation_end_date: 30/09/2008
validation_start_date: 01/10/2003
zero_center_target: true
